name: audio_player_package_example
description: Example app for the audio_player_package
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_player_package:
    path: ../   # Uses the package from the parent folder

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
