name: audio_player_package_example
description: Example app for the audio_player_package
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_player_package:
    path: ../   # Uses the package from the parent folder
  get_it: 8.2.0
  equatable: 2.0.7
  flutter_bloc: 9.1.1
  injectable: 2.5.1
  json_annotation: 4.9.0
  freezed: 3.0.6
  freezed_annotation: ^3.1.0
  bloc_concurrency: 0.3.0
  get_storage: 2.1.1
  collection: 1.19.1
  flutter_svg: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.3.0
  build_runner: ^2.4.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
